# Kind 10002: Relay List
name: "Relay List"
description: "User's relay list"
required_tags: []
optional_tags: ["r", "read", "write"]
content_validation:
  type: "empty"
  max_length: 0
quality_rules:
  - name: "valid_relay_urls"
    weight: 1.0
    description: "r tags must contain valid relay URLs"
  - name: "empty_content"
    weight: 0.9
    description: "Content should be empty"
replaceable: true
ephemeral: false
