# Kind 30023: Long-form Content
name: "Long-form Content"
description: "Long-form articles and posts"
required_tags: ["d"]
optional_tags: ["title", "summary", "image", "published_at", "a", "e", "p", "t"]
content_validation:
  type: "text"
  max_length: 100000
  min_length: 100
quality_rules:
  - name: "valid_d_tag"
    weight: 1.0
    description: "Must have valid d tag for addressability"
  - name: "substantial_content"
    weight: 0.8
    description: "Content should be substantial for long-form"
replaceable: true
ephemeral: false
