# Kind 30041: Publication Content
name: "Publication Content"
description: "Sections, chapters, or episodes of publications"
required_tags: ["d", "title"]
optional_tags: ["wikilink", "a", "e", "p", "t", "summary", "image", "published_on", "published_by", "version", "type"]
content_validation:
  type: "text"
  max_length: 100000
  min_length: 10
quality_rules:
  - name: "valid_d_tag"
    weight: 1.0
    description: "Must have valid d tag for addressability"
  - name: "substantial_content"
    weight: 0.8
    description: "Content should be substantial"
replaceable: true
ephemeral: false
