# Kind 30040: Publication Index
name: "Publication Index"
description: "Index of publication content"
required_tags: ["d", "title", "a", "auto-update"]
optional_tags: ["p", "E", "source", "i", "version", "type", "published_on", "published_by", "image", "summary", "t"]
content_validation:
  type: "empty"
  max_length: 0
quality_rules:
  - name: "valid_d_tag"
    weight: 1.0
    description: "Must have valid d tag for addressability"
  - name: "valid_references"
    weight: 0.9
    description: "Should reference valid content with a tags"
replaceable: true
ephemeral: false
