# Kind 30040: Publication Index
name: "Publication Index"
description: "Index of publication content"
required_tags: ["d"]
optional_tags: ["a", "e", "p", "title", "summary"]
content_validation:
  type: "text"
  max_length: 10000
  min_length: 1
quality_rules:
  - name: "valid_d_tag"
    weight: 1.0
    description: "Must have valid d tag for addressability"
  - name: "valid_references"
    weight: 0.9
    description: "Should reference valid content with a tags"
replaceable: true
ephemeral: false
