# Kind 30042: Drive Event
name: "Drive Event"
description: "File system drive root"
required_tags: ["d"]
optional_tags: ["description", "a"]
content_validation:
  type: "empty"
  max_length: 0
quality_rules:
  - name: "valid_d_tag"
    weight: 1.0
    description: "Must have valid d tag for addressability"
  - name: "empty_content"
    weight: 0.9
    description: "Content should be empty"
replaceable: true
ephemeral: false
