# Mercury Relay Configuration

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s

# Tor Configuration
tor:
  enabled: true
  data_dir: "/var/lib/tor"
  control_port: 9051
  socks_port: 9050
  hidden_service_dir: "/var/lib/tor/mercury_relay"
  hidden_service_port: 80

# I2P Configuration
i2p:
  enabled: true
  sam_port: 7656
  sam_host: "127.0.0.1"
  tunnel_name: "mercury_relay"
  tunnel_port: 8080

# SSH Configuration
ssh:
  enabled: ${SSH_ENABLED:-false}
  key_storage:
    key_dir: "${SSH_KEY_DIR:-./ssh-keys}"
    private_key_ext: ".pem"
    public_key_ext: ".pub"
    key_size: ${SSH_KEY_SIZE:-2048}
    key_type: "${SSH_KEY_TYPE:-rsa}"
  connection:
    host: "${SSH_HOST:-localhost}"
    port: ${SSH_PORT:-22}
    username: "${SSH_USERNAME:-mercury}"
    timeout: "${SSH_TIMEOUT:-30s}"
    keep_alive: "${SSH_KEEP_ALIVE:-30s}"
    max_retries: ${SSH_MAX_RETRIES:-3}
    retry_delay: "${SSH_RETRY_DELAY:-5s}"
    compression: ${SSH_COMPRESSION:-false}
    banner: "Mercury Relay SSH Server"
  terminal_interface:
    enabled: ${SSH_TERMINAL_ENABLED:-true}
    port: ${SSH_TERMINAL_PORT:-2222}
    host: "${SSH_TERMINAL_HOST:-localhost}"
    interactive: ${SSH_TERMINAL_INTERACTIVE:-true}
    log_level: "${SSH_TERMINAL_LOG_LEVEL:-info}"
  authentication:
    require_auth: ${SSH_REQUIRE_AUTH:-true}
    api_key: "${SSH_API_KEY:-admin-ssh-key-2024}"
    basic_auth_user: "${SSH_BASIC_AUTH_USER:-admin}"
    basic_auth_pass: "${SSH_BASIC_AUTH_PASS:-mercury-ssh-2024}"
    authorized_pubkeys:
      - "${SSH_AUTHORIZED_PUBKEY_1:-}"
      - "${SSH_AUTHORIZED_PUBKEY_2:-}"
    allow_localhost: ${SSH_ALLOW_LOCALHOST:-true}

# RabbitMQ Configuration
rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"
  exchange_name: "nostr_events"
  queue_name: "event_queue"
  dlx_name: "nostr_dlx"
  ttl: "28h"

# Redis Configuration
redis:
  host: "redis:6379"
  password: ""
  db: 0
  ttl: "28h"

# XFTP Configuration
xftp:
  enabled: true
  server_url: "xftp://localhost:443"
  storage_dir: "/srv/xftp"
  ttl: "48h"

# PostgreSQL Configuration
postgres:
  host: "postgres:5432"
  user: "mercury"
  password: "mercury"
  dbname: "mercury_relay"
  sslmode: "disable"

# Quality Control
quality:
  spam_threshold: 0.7
  rate_limit_per_minute: 60
  max_content_length: 10000
  quarantine_suspicious: true

# Access Control
access:
  admin_npubs:
    - "${MERCURY_ADMIN_NPUBS:-npub1m4ny6hjqzepn4rxknuq94c2gpqzr29ufkkw7ttcxyak7v43n6vvsajc2jl}"
  update_interval: "${ACCESS_UPDATE_INTERVAL:-1h}"
  relay_url: "${ACCESS_RELAY_URL:-https://relay.damus.io}"
  allow_public_read: "${ACCESS_PUBLIC_READ:-true}"
  allow_public_write: "${ACCESS_PUBLIC_WRITE:-false}"

# Admin Interface
admin:
  enabled: true
  port: 8081
  api_key: "change_this_secret_key"

# REST API Configuration
rest_api:
  enabled: true
  port: 8082
  cors_enabled: true
  cors_origins: ["*"]
  rate_limit_per_minute: 100
  endpoints:
    events: "/api/v1/events"
    query: "/api/v1/query"
    publish: "/api/v1/publish"
    ebooks: "/api/v1/ebooks"
    ebook_content: "/api/v1/ebooks/{id}/content"
    ebook_epub: "/api/v1/ebooks/{id}/epub"
    health: "/api/v1/health"
    stats: "/api/v1/stats"
  ebook_optimization:
    enabled: true
    cache_duration: "1h"
    max_file_size: "50MB"
    supported_formats: ["epub", "pdf", "mobi", "txt"]

# gRPC Configuration
grpc:
  enabled: ${GRPC_ENABLED:-true}
  server_host: ${GRPC_SERVER_HOST:-localhost}
  server_port: ${GRPC_SERVER_PORT:-9090}
  timeout: "30s"
  max_retries: 3
  retry_interval: "5s"
  tls_enabled: ${GRPC_TLS_ENABLED:-false}
  cert_file: ${GRPC_CERT_FILE:-""}
  key_file: ${GRPC_KEY_FILE:-""}
  keepalive_time: "30s"
  keepalive_timeout: "5s"
  max_message_size: 4194304  # 4MB
  compression_enabled: true

# Streaming Configuration
streaming:
  enabled: ${STREAMING_ENABLED:-true}
  upstream_relays: ${UPSTREAM_RELAYS:-"wss://theforest.nostr1.com,wss://orlay-relay.imwald.eu,wss://nostr.land,wss://nostr21.com"}
  transport_methods:
    websocket: true
    tor: true
    i2p: true
    ssh: true  # SSH tunneling for secure connections
    http_streaming: true  # HTTP streaming for server-side rendering
    sse: true  # Server-Sent Events for real-time updates
    grpc: true  # gRPC for high-performance communication
  connection_pool_size: 10
  reconnect_interval: "30s"
  timeout: "60s"

# Logging
logging:
  level: "info"
  format: "json"
  file: "/var/log/mercury-relay.log"
