version: '3.8'

services:
  mercury-relay:
    build: .
    container_name: mercury-relay
    restart: unless-stopped
    ports:
      - "8080:8080"  # Nostr WebSocket
      - "8081:8081"  # Admin API
      - "8082:8082"  # REST API
    environment:
      - NOSTR_RELAY_PORT=8080
      - ADMIN_PORT=8081
      - REST_API_PORT=8082
      - LOG_LEVEL=info
      - STREAMING_ENABLED=true
      - UPSTREAM_RELAYS=wss://theforest.nostr1.com,wss://orlay-relay.imwald.eu,wss://nostr.land,wss://nostr21.com
      - TOR_ENABLED=true
      - XFTP_ENABLED=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml:ro
      - ./nostr-event-kinds.yaml:/app/nostr-event-kinds.yaml:ro
    networks:
      - mercury-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Tor hidden service
  tor:
    image: dperson/torproxy:latest
    container_name: mercury-tor
    restart: unless-stopped
    ports:
      - "9050:9050"  # SOCKS proxy
      - "9051:9051"  # Control port
    volumes:
      - tor_data:/var/lib/tor
      - ./tor-config:/etc/tor:ro
    networks:
      - mercury-network
    environment:
      - TOR_PROXY=true
      - TOR_SERVICE=true
    command: >
      sh -c "
        echo 'HiddenServiceDir /var/lib/tor/mercury_relay' >> /etc/tor/torrc &&
        echo 'HiddenServicePort 80 mercury-relay:8080' >> /etc/tor/torrc &&
        echo 'HiddenServicePort 8081 mercury-relay:8081' >> /etc/tor/torrc &&
        echo 'HiddenServicePort 8082 mercury-relay:8082' >> /etc/tor/torrc &&
        tor -f /etc/tor/torrc
      "

  # XFTP file storage
  xftp:
    image: alpine:latest
    container_name: mercury-xftp
    restart: unless-stopped
    ports:
      - "8083:8083"
    volumes:
      - xftp_data:/var/lib/xftp
      - ./xftp-config:/etc/xftp:ro
    networks:
      - mercury-network
    command: >
      sh -c "
        apk add --no-cache python3 py3-pip &&
        pip3 install flask requests &&
        python3 -m http.server 8083 --directory /var/lib/xftp
      "
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: mercury-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mercury-network
    command: redis-server --appendonly yes

  # PostgreSQL for storage
  postgres:
    image: postgres:15-alpine
    container_name: mercury-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mercury_relay
      - POSTGRES_USER=mercury
      - POSTGRES_PASSWORD=change_this_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mercury-network

  # Apache reverse proxy
  apache:
    image: httpd:2.4-alpine
    container_name: mercury-apache
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache.conf:/usr/local/apache2/conf/extra/mercury-relay.conf:ro
      - ./apache-docker.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - mercury-relay
      - tor
      - xftp
    networks:
      - mercury-network

volumes:
  tor_data:
  xftp_data:
  redis_data:
  postgres_data:

networks:
  mercury-network:
    driver: bridge
