# Nostr Event Kinds Quality Control Configuration
# This file defines global quality control settings
# Individual event kind definitions are now loaded dynamically from configs/kinds/*.yml files

# Global quality control settings
global_quality:
  # Spam detection
  spam_detection:
    enabled: true
    threshold: 0.7
    rules:
      - name: "repetitive_content"
        weight: 0.8
        description: "Detect repetitive or identical content"
      - name: "excessive_mentions"
        weight: 0.6
        description: "Detect excessive use of mentions"
      - name: "suspicious_patterns"
        weight: 0.9
        description: "Detect suspicious posting patterns"

  # Rate limiting
  rate_limiting:
    enabled: true
    events_per_minute: 60
    burst_limit: 10
    per_kind_limits:
      0: 1  # User metadata - very limited
      1: 60  # Text notes - normal limit
      3: 1   # Follow list - very limited
      4: 30  # DMs - moderate limit

  # Content validation
  content_validation:
    max_content_length: 10000
    min_content_length: 1
    allowed_encodings: ["utf-8"]
    forbidden_patterns:
      - "spam_pattern_1"
      - "spam_pattern_2"

  # Tag validation
  tag_validation:
    max_tags_per_event: 100
    max_tag_length: 1000
    required_tag_formats:
      "e": "^[a-f0-9]{64}$"  # Event ID must be 64 hex chars
      "p": "^[a-f0-9]{64}$"  # Pubkey must be 64 hex chars
      "a": "^[0-9]+:[a-f0-9]{64}:.*$"  # Address format

# Relay-specific settings
relay_settings:
  # Storage policies
  storage:
    regular_events: true
    replaceable_events: true
    ephemeral_events: false
    addressable_events: true

  # Retention policies
  retention:
    regular_events: "28d"
    replaceable_events: "7d"
    addressable_events: "28d"

  # Quarantine settings
  quarantine:
    enabled: true
    auto_quarantine_threshold: 0.5
    manual_review_threshold: 0.3
    quarantine_duration: "24h"